- hosts: localhost
  tasks:
- name: ls -l /var/lib/jenkins/workspace/BackendDev/Deploy/Publish/Development/
  find:
    paths: /var/lib/jenkins/workspace/BackendDev/Deploy/Publish/Development/
    patterns: "*"
    recurse: no
    file_type: directory
  register: found_directories

- debug:
    msg: "{{ [item.path] }} "
  with_items: "{{ found_directories.files }}"


