- hosts: backendevinfra
  vars:
   dirDeploy: C:\ServiciosSA\DEV
   workSpace: /var/lib/jenkins/workspace/BackendDev/Deploy/Publish/Development/
   Environment: DEV

  tasks:

### Stopeo Servicios Backend
### Stop Services DogWatch

   - name: Stop 'DogWatcherService{{ Environment }}'
     win_service:
       name: 'DogWatcherService{{ Environment }}'
       state: stopped

### Stop Services webapi
### ApiGateway
   - name: get info on service 'ApiGateway{{ Environment }}'
     win_service:
       name: 'ApiGateway{{ Environment }}'
     register: 'ApiGateway{{ Environment }}_service'  
   - name: Stop 'ApiGateway{{ Environment }}'
     win_service:
       name: 'ApiGateway{{ Environment }}'
       state: stopped
     when: 'ApiGateway{{ Environment }}_service.exists'

### ApiGatewayPortal
   - name: get info on service 'ApiGatewayPortal{{ Environment }}'
     win_service:
       name: 'ApiGatewayPortal{{ Environment }}'
     register: 'ApiGatewayPortal{{ Environment }}_service' 
   - name: Stop 'ApiGatewayPortal{{ Environment }}'
     win_service:
       name: 'ApiGatewayPortal{{ Environment }}'
       state: stopped
     when: 'ApiGatewayPortal{{ Environment }}_service.exists'

### AuthenticationService
   - name: get info on service 'AuthenticationService{{ Environment }}'
     win_service:
       name: 'AuthenticationService{{ Environment }}'
     register: 'AuthenticationService{{ Environment }}_service' 
   - name: Stop 'AuthenticationService{{ Environment }}'
     win_service:
       name: 'AuthenticationService{{ Environment }}'
       state: stopped
     when: 'AuthenticationService{{ Environment }}_service.exists'
     
### AutorizadorGenerico
   - name: get info on service 'AuthenticationService{{ Environment }}'
     win_service:
       name: 'AuthenticationService{{ Environment }}'
     register: 'AuthenticationService{{ Environment }}_service' 
   - name: Stop 'AutorizadorGenerico{{ Environment }}'
     win_service:
       name: 'AutorizadorGenerico{{ Environment }}'
       state: stopped
     when: 'AutorizadorGenerico{{ Environment }}_service.exists'

### SanatorioAllendeBackEnd
   - name: get info on service 'SanatorioAllendeBackEnd{{ Environment }}'
     win_service:
       name: 'SanatorioAllendeBackEnd{{ Environment }}'
     register: 'SanatorioAllendeBackEnd{{ Environment }}_service'
   - name: Stop 'SanatorioAllendeBackEnd{{ Environment }}'
     win_service:
       name: 'SanatorioAllendeBackEnd{{ Environment }}'
       state: stopped
     when: 'SanatorioAllendeBackEnd{{ Environment }}_service.exists'

### SanatorioAllendeBackEndPortal
   - name: get info on service 'SanatorioAllendeBackEndPortal{{ Environment }}'
     win_service:
       name: 'SanatorioAllendeBackEndPortal{{ Environment }}'
     register: 'SanatorioAllendeBackEndPortal{{ Environment }}_service'
   - name: Stop 'SanatorioAllendeBackEndPortal{{ Environment }}'
     win_service:
       name: 'SanatorioAllendeBackEndPortal{{ Environment }}'
       state: stopped
     when: 'SanatorioAllendeBackEndPortal{{ Environment }}_service.exists'

### Terminologia
   - name: get info on service 'Terminologia{{ Environment }}'
     win_service:
       name: 'Terminologia{{ Environment }}'
     register: 'Terminologia{{ Environment }}_service'
   - name: Stop 'Terminologia{{ Environment }}'
     win_service:
       name: 'Terminologia{{ Environment }}'
       state: stopped
     when: 'Terminologia{{ Environment }}_service.exists'


### Stop Services workers
### BackupIMService
   - name: get info on service 'BackupIMService{{ Environment }}'
     win_service:
       name: 'BackupIMService{{ Environment }}'
     register: 'BackupIMService{{ Environment }}_service'
   - name: Stop 'BackupIMService{{ Environment }}'
     win_service:
       name: 'BackupIMService{{ Environment }}'
       state: stopped
     when: 'BackupIMService{{ Environment }}_service.exists'

### CacheTerminologia
   - name: get info on service 'CacheTerminologia{{ Environment }}'
     win_service:
       name: 'CacheTerminologia{{ Environment }}'
     register: 'CacheTerminologia{{ Environment }}_service'
   - name: Stop 'CacheTerminologia{{ Environment }}'
     win_service:
       name: 'CacheTerminologia{{ Environment }}'
       state: stopped
     when: 'CacheTerminologia{{ Environment }}_service.exists'

### ConfirmacionDeTurnosService
   - name: get info on service 'ConfirmacionDeTurnosService{{ Environment }}'
     win_service:
       name: 'ConfirmacionDeTurnosService{{ Environment }}'
     register: 'ConfirmacionDeTurnosService{{ Environment }}_service'
   - name: Stop 'ConfirmacionDeTurnosService{{ Environment }}'
     win_service:
       name: 'ConfirmacionDeTurnosService{{ Environment }}'
       state: stopped
     when: 'ConfirmacionDeTurnosService{{ Environment }}_service.exists'  

### FacturaElectronicaService
   - name: get info on service 'FacturaElectronicaService{{ Environment }}'
     win_service:
       name: 'FacturaElectronicaService{{ Environment }}'
     register: 'FacturaElectronicaService{{ Environment }}_service'
   - name: Stop 'FacturaElectronicaService{{ Environment }}'
     win_service:
       name: 'FacturaElectronicaService{{ Environment }}'
       state: stopped
     when: 'FacturaElectronicaService{{ Environment }}_service.exists'

### ImportadorDeFarmacosService
   - name: get info on service 'ImportadorDeFarmacosService{{ Environment }}'
     win_service:
       name: 'ImportadorDeFarmacosService{{ Environment }}'
     register: 'ImportadorDeFarmacosService{{ Environment }}_service'
   - name: Stop 'ImportadorDeFarmacosService{{ Environment }}'
     win_service:
       name: 'ImportadorDeFarmacosService{{ Environment }}'
       state: stopped
     when: 'ImportadorDeFarmacosService{{ Environment }}_service.exists'

### MessageIntegrationService
   - name: get info on service 'MessageIntegrationService{{ Environment }}'
     win_service:
       name: 'MessageIntegrationService{{ Environment }}'
     register: 'MessageIntegrationService{{ Environment }}_service'
   - name: Stop 'MessageIntegrationService{{ Environment }}'
     win_service:
       name: 'MessageIntegrationService{{ Environment }}'
       state: stopped
     when: 'MessageIntegrationService{{ Environment }}_service.exists'

### NotificacionDeSolicitudesPendientes
   - name: get info on service 'NotificacionDeSolicitudesPendientes{{ Environment }}'
     win_service:
       name: 'NotificacionDeSolicitudesPendientes{{ Environment }}'
     register: 'NotificacionDeSolicitudesPendientes{{ Environment }}_service'
   - name: Stop 'NotificacionDeSolicitudesPendientes{{ Environment }}'
     win_service:
       name: 'NotificacionDeSolicitudesPendientes{{ Environment }}'
       state: stopped
     when: 'NotificacionDeSolicitudesPendientes{{ Environment }}_service.exists'

### ReprocesadorDeIntegraciones
   - name: get info on service 'ReprocesadorDeIntegraciones{{ Environment }}'
     win_service:
       name: 'ReprocesadorDeIntegraciones{{ Environment }}'
     register: 'ReprocesadorDeIntegraciones{{ Environment }}_service'
   - name: Stop 'ReprocesadorDeIntegraciones{{ Environment }}'
     win_service:
       name: 'ReprocesadorDeIntegraciones{{ Environment }}'
       state: stopped
     when: 'ReprocesadorDeIntegraciones{{ Environment }}_service.exists'

### ReprocesoAutorizacionesPendientesAud
   - name: get info on service 'ReprocesoAutorizacionesPendientesAud{{ Environment }}'
     win_service:
       name: 'ReprocesoAutorizacionesPendientesAud{{ Environment }}'
     register: 'ReprocesoAutorizacionesPendientesAud{{ Environment }}_service'
   - name: Stop 'ReprocesoAutorizacionesPendientesAud{{ Environment }}'
     win_service:
       name: 'ReprocesoAutorizacionesPendientesAud{{ Environment }}'
       state: stopped
     when: 'ReprocesoAutorizacionesPendientesAud{{ Environment }}_service.exists'

### RisIntegrationService
   - name: get info on service 'RisIntegrationService{{ Environment }}'
     win_service:
       name: 'RisIntegrationService{{ Environment }}'
     register: 'RisIntegrationService{{ Environment }}_service'
   - name: Stop 'RisIntegrationService{{ Environment }}'
     win_service:
       name: 'RisIntegrationService{{ Environment }}'
       state: stopped
     when: 'RisIntegrationService{{ Environment }}_service.exists'


### Elimino Carpetas de Servicios
   - name: Delete All Folders
     win_file:
       path: "{{ dirDeploy }}"
       state: absent
   - name: Create All Folders
     win_file:
       path: "{{ dirDeploy }}"
       state: directory

### Copio Carpetas de nuevo Deploy

   - name: Copy ApiGatewayPortalService
     win_copy:
       src: '{{ workSpace }}ApiGatewayPortalService'
       dest: "{{ dirDeploy }}"

   - name: Copy ApiGatewayService
     win_copy:
       src: '{{ workSpace }}ApiGatewayService'
       dest: "{{ dirDeploy }}"

   - name: Copy AuthenticationService
     win_copy:
       src: '{{ workSpace }}AuthenticationService'
       dest: "{{ dirDeploy }}"

   - name: Copy BackendService
     win_copy:
       src: '{{ workSpace }}BackendService'
       dest: "{{ dirDeploy }}"

   - name: Copy BackupIMService
     win_copy:
       src: '{{ workSpace }}BackupIMService'
       dest: "{{ dirDeploy }}"
  
   - name: Copy CacheTerminologiaService
     win_copy:
       src: '{{ workSpace }}CacheTerminologiaService'
       dest: "{{ dirDeploy }}"

   - name: Copy ConfirmacionDeTurnosService
     win_copy:
       src: '{{ workSpace }}ConfirmacionDeTurnosService'
       dest: "{{ dirDeploy }}"
  
   - name: Copy FacturaElectronicaService
     win_copy:
       src: '{{ workSpace }}FacturaElectronicaService'
       dest: "{{ dirDeploy }}"

   - name: Copy ImportadorDeFarmacosService
     win_copy:
       src: '{{ workSpace }}ImportadorDeFarmacosService'
       dest: "{{ dirDeploy }}"

   - name: Copy MessageIntegrationService
     win_copy:
       src: '{{ workSpace }}MessageIntegrationService'
       dest: "{{ dirDeploy }}"

   - name: Copy NotificacionDeSolicitudesPendientesService
     win_copy:
       src: '{{ workSpace }}NotificacionDeSolicitudesPendientesService'
       dest: "{{ dirDeploy }}"

   - name: Copy PortalService
     win_copy:
       src: '{{ workSpace }}PortalService'
       dest: "{{ dirDeploy }}"

   - name: Copy ReprocesadorDeIntegraciones
     win_copy:
       src: '{{ workSpace }}ReprocesadorDeIntegraciones'
       dest: "{{ dirDeploy }}"

   - name: Copy ReprocesoAutorizacionesPendientesAud
     win_copy:
       src: '{{ workSpace }}ReprocesoAutorizacionesPendientesAud'
       dest: "{{ dirDeploy }}"

   - name: Copy RisIntegrationService
     win_copy:
       src: '{{ workSpace }}RisIntegrationService'
       dest: "{{ dirDeploy }}"

   - name: Copy TerminologiaService
     win_copy:
       src: '{{ workSpace }}TerminologiaService'
       dest: "{{ dirDeploy }}"

### Starteo Servicios Backend
### Start Services webapi
### ApiGateway
   - name: get info on service 'ApiGateway{{ Environment }}'
     win_service:
       name: 'ApiGateway{{ Environment }}'
     register: 'ApiGateway{{ Environment }}_service'
   - name: Inicio ApiGateway
     win_service:
       name: 'ApiGateway{{ Environment }}'
     state: started
     when: 'ApiGateway{{ Environment }}_service.exists'

### ApiGatewayPortal
   - name: get info on service 'ApiGatewayPortal{{ Environment }}'
     win_service:
       name: 'ApiGatewayPortal{{ Environment }}'
     register: 'ApiGatewayPortal{{ Environment }}_service' 
   - name: Start 'ApiGatewayPortal{{ Environment }}'
     win_service:
       name: 'ApiGatewayPortal{{ Environment }}'
       state: started
     when: 'ApiGatewayPortal{{ Environment }}_service.exists'

### AuthenticationService
   - name: get info on service 'AuthenticationService{{ Environment }}'
     win_service:
       name: 'AuthenticationService{{ Environment }}'
     register: 'AuthenticationService{{ Environment }}_service' 
   - name: Start 'AuthenticationService{{ Environment }}'
     win_service:
       name: 'AuthenticationService{{ Environment }}'
       state: started
     when: 'AuthenticationService{{ Environment }}_service.exists'
     
### AutorizadorGenerico
   - name: get info on service 'AuthenticationService{{ Environment }}'
     win_service:
       name: 'AuthenticationService{{ Environment }}'
     register: 'AuthenticationService{{ Environment }}_service' 
   - name: Start 'AutorizadorGenerico{{ Environment }}'
     win_service:
       name: 'AutorizadorGenerico{{ Environment }}'
       state: started
     when: 'AutorizadorGenerico{{ Environment }}_service.exists'

### SanatorioAllendeBackEnd
   - name: get info on service 'SanatorioAllendeBackEnd{{ Environment }}'
     win_service:
       name: 'SanatorioAllendeBackEnd{{ Environment }}'
     register: 'SanatorioAllendeBackEnd{{ Environment }}_service'
   - name: Start 'SanatorioAllendeBackEnd{{ Environment }}'
     win_service:
       name: 'SanatorioAllendeBackEnd{{ Environment }}'
       state: started
     when: 'SanatorioAllendeBackEnd{{ Environment }}_service.exists'

### SanatorioAllendeBackEndPortal
   - name: get info on service 'SanatorioAllendeBackEndPortal{{ Environment }}'
     win_service:
       name: 'SanatorioAllendeBackEndPortal{{ Environment }}'
     register: 'SanatorioAllendeBackEndPortal{{ Environment }}_service'
   - name: Start 'SanatorioAllendeBackEndPortal{{ Environment }}'
     win_service:
       name: 'SanatorioAllendeBackEndPortal{{ Environment }}'
       state: started
     when: 'SanatorioAllendeBackEndPortal{{ Environment }}_service.exists'

### Terminologia
   - name: get info on service 'Terminologia{{ Environment }}'
     win_service:
       name: 'Terminologia{{ Environment }}'
     register: 'Terminologia{{ Environment }}_service'
   - name: Start 'Terminologia{{ Environment }}'
     win_service:
       name: 'Terminologia{{ Environment }}'
       state: started
     when: 'Terminologia{{ Environment }}_service.exists'


### Stop Services workers
### BackupIMService
   - name: get info on service 'BackupIMService{{ Environment }}'
     win_service:
       name: 'BackupIMService{{ Environment }}'
     register: 'BackupIMService{{ Environment }}_service'
   - name: Start 'BackupIMService{{ Environment }}'
     win_service:
       name: 'BackupIMService{{ Environment }}'
       state: started
     when: 'BackupIMService{{ Environment }}_service.exists'

### CacheTerminologia
   - name: get info on service 'CacheTerminologia{{ Environment }}'
     win_service:
       name: 'CacheTerminologia{{ Environment }}'
     register: 'CacheTerminologia{{ Environment }}_service'
   - name: Start 'CacheTerminologia{{ Environment }}'
     win_service:
       name: 'CacheTerminologia{{ Environment }}'
       state: started
     when: 'CacheTerminologia{{ Environment }}_service.exists'

### ConfirmacionDeTurnosService
   - name: get info on service 'ConfirmacionDeTurnosService{{ Environment }}'
     win_service:
       name: 'ConfirmacionDeTurnosService{{ Environment }}'
     register: 'ConfirmacionDeTurnosService{{ Environment }}_service'
   - name: Start 'ConfirmacionDeTurnosService{{ Environment }}'
     win_service:
       name: 'ConfirmacionDeTurnosService{{ Environment }}'
       state: started
     when: 'ConfirmacionDeTurnosService{{ Environment }}_service.exists'  

### FacturaElectronicaService
   - name: get info on service 'FacturaElectronicaService{{ Environment }}'
     win_service:
       name: 'FacturaElectronicaService{{ Environment }}'
     register: 'FacturaElectronicaService{{ Environment }}_service'
   - name: Start 'FacturaElectronicaService{{ Environment }}'
     win_service:
       name: 'FacturaElectronicaService{{ Environment }}'
       state: started
     when: 'FacturaElectronicaService{{ Environment }}_service.exists'

### ImportadorDeFarmacosService
   - name: get info on service 'ImportadorDeFarmacosService{{ Environment }}'
     win_service:
       name: 'ImportadorDeFarmacosService{{ Environment }}'
     register: 'ImportadorDeFarmacosService{{ Environment }}_service'
   - name: Start 'ImportadorDeFarmacosService{{ Environment }}'
     win_service:
       name: 'ImportadorDeFarmacosService{{ Environment }}'
       state: started
     when: 'ImportadorDeFarmacosService{{ Environment }}_service.exists'

### MessageIntegrationService
   - name: get info on service 'MessageIntegrationService{{ Environment }}'
     win_service:
       name: 'MessageIntegrationService{{ Environment }}'
     register: 'MessageIntegrationService{{ Environment }}_service'
   - name: Start 'MessageIntegrationService{{ Environment }}'
     win_service:
       name: 'MessageIntegrationService{{ Environment }}'
       state: started
     when: 'MessageIntegrationService{{ Environment }}_service.exists'

### NotificacionDeSolicitudesPendientes
   - name: get info on service 'NotificacionDeSolicitudesPendientes{{ Environment }}'
     win_service:
       name: 'NotificacionDeSolicitudesPendientes{{ Environment }}'
     register: 'NotificacionDeSolicitudesPendientes{{ Environment }}_service'
   - name: Start 'NotificacionDeSolicitudesPendientes{{ Environment }}'
     win_service:
       name: 'NotificacionDeSolicitudesPendientes{{ Environment }}'
       state: started
     when: 'NotificacionDeSolicitudesPendientes{{ Environment }}_service.exists'

### ReprocesadorDeIntegraciones
   - name: get info on service 'ReprocesadorDeIntegraciones{{ Environment }}'
     win_service:
       name: 'ReprocesadorDeIntegraciones{{ Environment }}'
     register: 'ReprocesadorDeIntegraciones{{ Environment }}_service'
   - name: Start 'ReprocesadorDeIntegraciones{{ Environment }}'
     win_service:
       name: 'ReprocesadorDeIntegraciones{{ Environment }}'
       state: started
     when: 'ReprocesadorDeIntegraciones{{ Environment }}_service.exists'

### ReprocesoAutorizacionesPendientesAud
   - name: get info on service 'ReprocesoAutorizacionesPendientesAud{{ Environment }}'
     win_service:
       name: 'ReprocesoAutorizacionesPendientesAud{{ Environment }}'
     register: 'ReprocesoAutorizacionesPendientesAud{{ Environment }}_service'
   - name: Start 'ReprocesoAutorizacionesPendientesAud{{ Environment }}'
     win_service:
       name: 'ReprocesoAutorizacionesPendientesAud{{ Environment }}'
       state: started
     when: 'ReprocesoAutorizacionesPendientesAud{{ Environment }}_service.exists'

### RisIntegrationService
   - name: get info on service 'RisIntegrationService{{ Environment }}'
     win_service:
       name: 'RisIntegrationService{{ Environment }}'
     register: 'RisIntegrationService{{ Environment }}_service'
   - name: Start 'RisIntegrationService{{ Environment }}'
     win_service:
       name: 'RisIntegrationService{{ Environment }}'
       state: started
     when: 'RisIntegrationService{{ Environment }}_service.exists'

### Start Services DogWatch

   - name: Start 'DogWatcherService{{ Environment }}'
     win_service:
       name: 'DogWatcherService{{ Environment }}'
       state: started