- hosts: backendevinfra
  vars:
   dirDeploy: C:\ServiciosSA\DEV\
   workSpace: /var/lib/jenkins/workspace/BackendDev/Deploy/Publish/Development/
   Environment: DEV

  tasks:

### Stopeo Servicios Backend
### Stop Services DogWatch

   - name: Stop DogWatcherServiceDEV
     win_service:
       name: DogWatcherServiceDEV
       state: stopped

### Stop Services webapi
### ApiGateway
   - name: get info on service ApiGatewayDEV
     win_service:
       name: ApiGatewayDEV
     register: ApiGatewayDEV_service  
   - name: Stop ApiGatewayDEV
     win_service:
       name: ApiGatewayDEV
       state: stopped
     when: ApiGatewayDEV_service.exists

### ApiGatewayPortal
   - name: get info on service ApiGatewayPortalDEV
     win_service:
       name: ApiGatewayPortalDEV
     register: ApiGatewayPortalDEV_service
   - name: Stop ApiGatewayPortalDEV
     win_service:
       name: ApiGatewayPortalDEV
       state: stopped
     when: ApiGatewayPortalDEV_service.exists

### AuthenticationService
   - name: get info on service AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
     register: AuthenticationServiceDEV_service
   - name: Stop AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
       state: stopped
     when: AuthenticationServiceDEV_service.exists
     
### AutorizadorGenerico
   - name: get info on service AutorizadorGenericoDEV
     win_service:
       name: AutorizadorGenericoDEV
     register: AutorizadorGenericoDEV_service
   - name: Stop AutorizadorGenericoDEV
     win_service:
       name: AutorizadorGenericoDEV
       state: stopped
     when: AutorizadorGenericoDEV_service.exists

### SanatorioAllendeBackEnd
   - name: get info on service SanatorioAllendeBackEndENV
     win_service:
       name: SanatorioAllendeBackEndENV
     register: SanatorioAllendeBackEndENV_service
   - name: Stop SanatorioAllendeBackEndENV
     win_service:
       name: SanatorioAllendeBackEndENV
       state: stopped
     when: SanatorioAllendeBackEndENV_service.exists

### SanatorioAllendeBackEndPortal
   - name: get info on service SanatorioAllendeBackEndPortalDEV
     win_service:
       name: SanatorioAllendeBackEndPortalDEV
     register: SanatorioAllendeBackEndPortalDEV_service
   - name: Stop SanatorioAllendeBackEndPortalDEV
     win_service:
       name: SanatorioAllendeBackEndPortalDEV
       state: stopped
     when: SanatorioAllendeBackEndPortalDEV_service.exists

### Terminologia
   - name: get info on service TerminologiaDEV
     win_service:
       name: TerminologiaDEV
     register: TerminologiaDEV_service
   - name: Stop TerminologiaDEV
     win_service:
       name: TerminologiaDEV
       state: stopped
     when: TerminologiaDEV_service.exists


### Stop Services workers
### BackupIMService
   - name: get info on service BackupIMServiceDEV
     win_service:
       name: BackupIMServiceDEV
     register: BackupIMServiceDEV_service
   - name: Stop BackupIMServiceDEV
     win_service:
       name: BackupIMServiceDEV
       state: stopped
     when: BackupIMServiceDEV_service.exists

### CacheTerminologia
   - name: get info on service CacheTerminologiaDEV
     win_service:
       name: CacheTerminologiaDEV
     register: CacheTerminologiaDEV_service
   - name: Stop CacheTerminologiaDEV
     win_service:
       name: CacheTerminologiaDEV
       state: stopped
     when: CacheTerminologiaDEV_service.exists

### ConfirmacionDeTurnosService
   - name: get info on service ConfirmacionDeTurnosServiceDEV
     win_service:
       name: ConfirmacionDeTurnosServiceDEV
     register: ConfirmacionDeTurnosServiceDEV_service
   - name: Stop ConfirmacionDeTurnosServiceDEV
     win_service:
       name: ConfirmacionDeTurnosServiceDEV
       state: stopped
     when: ConfirmacionDeTurnosServiceDEV_service.exists

### FacturaElectronicaService
   - name: get info on service FacturaElectronicaServiceDEV
     win_service:
       name: FacturaElectronicaServiceDEV
     register: FacturaElectronicaServiceDEV_service
   - name: Stop FacturaElectronicaServiceDEV
     win_service:
       name: FacturaElectronicaServiceDEV
       state: stopped
     when: FacturaElectronicaServiceDEV_service.exists

### ImportadorDeFarmacosService
   - name: get info on service ImportadorDeFarmacosServiceDEV
     win_service:
       name: ImportadorDeFarmacosServiceDEV
     register: ImportadorDeFarmacosServiceDEV_service
   - name: Stop ImportadorDeFarmacosServiceDEV
     win_service:
       name: ImportadorDeFarmacosServiceDEV
       state: stopped
     when: ImportadorDeFarmacosServiceDEV_service.exists

### MessageIntegrationService
   - name: get info on service MessageIntegrationServiceDEV
     win_service:
       name: MessageIntegrationServiceDEV
     register: MessageIntegrationServiceDEV_service
   - name: Stop MessageIntegrationServiceDEV
     win_service:
       name: MessageIntegrationServiceDEV
       state: stopped
     when: MessageIntegrationServiceDEV_service.exists

### NotificacionDeSolicitudesPendientes
   - name: get info on service NotificacionDeSolicitudesPendientesDEV
     win_service:
       name: NotificacionDeSolicitudesPendientesDEV
     register: NotificacionDeSolicitudesPendientesDEV_service
   - name: Stop NotificacionDeSolicitudesPendientesDEV
     win_service:
       name: NotificacionDeSolicitudesPendientesDEV
       state: stopped
     when: NotificacionDeSolicitudesPendientesDEV_service.exists

### ReprocesadorDeIntegraciones
   - name: get info on service ReprocesadorDeIntegracionesDEV
     win_service:
       name: ReprocesadorDeIntegracionesDEV
     register: ReprocesadorDeIntegracionesDEV_service
   - name: Stop ReprocesadorDeIntegracionesDEV
     win_service:
       name: ReprocesadorDeIntegracionesDEV
       state: stopped
     when: ReprocesadorDeIntegracionesDEV_service.exists

### ReprocesoAutorizacionesPendientesAud
   - name: get info on service ReprocesoAutorizacionesPendientesAudDEV
     win_service:
       name: ReprocesoAutorizacionesPendientesAudDEV
     register: ReprocesoAutorizacionesPendientesAudDEV_service
   - name: Stop ReprocesoAutorizacionesPendientesAudDEV
     win_service:
       name: ReprocesoAutorizacionesPendientesAudDEV
       state: stopped
     when: ReprocesoAutorizacionesPendientesAudDEV_service.exists

### RisIntegrationService
   - name: get info on service RisIntegrationServiceDEV
     win_service:
       name: RisIntegrationServiceDEV
     register: RisIntegrationServiceDEV_service
   - name: Stop RisIntegrationServiceDEV
     win_service:
       name: RisIntegrationServiceDEV
       state: stopped
     when: RisIntegrationServiceDEV_service.exists


### Elimino Carpetas de Servicios

   - name: Delete ApiGatewayPortal
     win_file:
       path: C:\ServiciosSA\DEV\ApiGatewayPortal
       state: absent
   - name: Delete ApiGateway
     win_file:
       path: C:\ServiciosSA\DEV\ApiGateway
       state: absent
   - name: Delete Authentication
     win_file:
       path: C:\ServiciosSA\DEV\Authentication
       state: absent
   - name: Delete Backend
     win_file:
       path: C:\ServiciosSA\DEV\Backend
       state: absent
   - name: Delete BackupIM
     win_file:
       path: C:\ServiciosSA\DEV\BackupIM
       state: absent
   - name: Delete CacheTerminologia
     win_file:
       path: C:\ServiciosSA\DEV\CacheTerminologia
       state: absent
   - name: Delete ConfirmacionDeTurnos
     win_file:
       path: C:\ServiciosSA\DEV\ConfirmacionDeTurnos
       state: absent
   - name: Delete NotificacionDeSolicitudesPendientes
     win_file:
       path: C:\ServiciosSA\DEV\NotificacionDeSolicitudesPendientes
       state: absent
   - name: Delete BackendPortal
     win_file:
       path: C:\ServiciosSA\DEV\BackendPortal
       state: absent
   - name: Delete ReprocesadorDeIntegraciones
     win_file:
       path: C:\ServiciosSA\DEV\ReprocesadorDeIntegraciones
       state: absent
   - name: Delete ReprocesoAutorizacionesPendientesAud
     win_file:
       path: C:\ServiciosSA\DEV\ReprocesoAutorizacionesPendientesAud
       state: absent
   - name: Delete RisIntegration
     win_file:
       path: C:\ServiciosSA\DEV\RisIntegration
       state: absent
   - name: Delete Terminologia
     win_file:
       path: C:\ServiciosSA\DEV\Terminologia
       state: absent

### Creo Carpetas de Servicios
   - name: Create ApiGatewayPortal
     win_file:
       path: C:\ServiciosSA\DEV\ApiGatewayPortal
       state: directory
   - name: Create ApiGateway
     win_file:
       path: C:\ServiciosSA\DEV\ApiGateway
       state: directory
   - name: Create Authentication
     win_file:
       path: C:\ServiciosSA\DEV\Authentication
       state: directory
   - name: Create Backend
     win_file:
       path: C:\ServiciosSA\DEV\Backend
       state: directory
   - name: Create BackupIM
     win_file:
       path: C:\ServiciosSA\DEV\BackupIM
       state: directory
   - name: Create CacheTerminologia
     win_file:
       path: C:\ServiciosSA\DEV\CacheTerminologia
       state: directory
   - name: Create ConfirmacionDeTurnos
     win_file:
       path: C:\ServiciosSA\DEV\ConfirmacionDeTurnos
       state: directory
   - name: Create NotificacionDeSolicitudesPendientes
     win_file:
       path: C:\ServiciosSA\DEV\NotificacionDeSolicitudesPendientes
       state: directory
   - name: Create Portal
     win_file:
       path: C:\ServiciosSA\DEV\Portal
       state: directory
   - name: Create ReprocesadorDeIntegraciones
     win_file:
       path: C:\ServiciosSA\DEV\ReprocesadorDeIntegraciones
       state: directory
   - name: Create ReprocesoAutorizacionesPendientesAud
     win_file:
       path: C:\ServiciosSA\DEV\ReprocesoAutorizacionesPendientesAud
       state: directory
   - name: Create RisIntegration
     win_file:
       path: C:\ServiciosSA\DEV\RisIntegration
       state: directory
   - name: Create Terminologia
     win_file:
       path: C:\ServiciosSA\DEV\Terminologia
       state: directory

### Copio Carpetas de nuevo Deploy

   - name: Copy ApiGatewayPortal
     win_copy:
       src: '{{ workSpace }}ApiGatewayPortal'
       dest: "{{ dirDeploy }}"

   - name: Copy ApiGateway
     win_copy:
       src: '{{ workSpace }}ApiGateway'
       dest: "{{ dirDeploy }}"

   - name: Copy Authentication
     win_copy:
       src: '{{ workSpace }}Authentication'
       dest: "{{ dirDeploy }}"

   - name: Copy BackEnd
     win_copy:
       src: '{{ workSpace }}BackEnd'
       dest: "{{ dirDeploy }}"

   - name: Copy BackupIM
     win_copy:
       src: '{{ workSpace }}BackupIM'
       dest: "{{ dirDeploy }}"
  
   - name: Copy CacheTerminologia
     win_copy:
       src: '{{ workSpace }}CacheTerminologia'
       dest: "{{ dirDeploy }}"

   - name: Copy ConfirmacionDeTurnos
     win_copy:
       src: '{{ workSpace }}ConfirmacionDeTurnos'
       dest: "{{ dirDeploy }}"
  
   - name: Copy FacturaElectronica
     win_copy:
       src: '{{ workSpace }}FacturaElectronica'
       dest: "{{ dirDeploy }}"

   - name: Copy ImportadorDeFarmacos
     win_copy:
       src: '{{ workSpace }}ImportadorDeFarmacos'
       dest: "{{ dirDeploy }}"

   - name: Copy MessageIntegration
     win_copy:
       src: '{{ workSpace }}MessageIntegration'
       dest: "{{ dirDeploy }}"

   - name: Copy NotificacionDeSolicitudesPendientes
     win_copy:
       src: '{{ workSpace }}NotificacionDeSolicitudesPendientes'
       dest: "{{ dirDeploy }}"

   - name: Copy BackEndPortal
     win_copy:
       src: '{{ workSpace }}BackEndPortal'
       dest: "{{ dirDeploy }}"

   - name: Copy ReprocesadorDeIntegraciones
     win_copy:
       src: '{{ workSpace }}ReprocesadorDeIntegraciones'
       dest: "{{ dirDeploy }}"

   - name: Copy ReprocesoAutorizacionesPendientesAud
     win_copy:
       src: '{{ workSpace }}ReprocesoAutorizacionesPendientesAud'
       dest: "{{ dirDeploy }}"

   - name: Copy RisIntegrationService
     win_copy:
       src: '{{ workSpace }}RisIntegrationService'
       dest: "{{ dirDeploy }}"

   - name: Copy Terminologia
     win_copy:
       src: '{{ workSpace }}Terminologia'
       dest: "{{ dirDeploy }}"

### Starteo Servicios Backend
### Start Services webapi
### ApiGateway
   - name: get info on service ApiGatewayDEV
     win_service:
       name: ApiGatewayDEV
     register: ApiGatewayDEV_service 
   - name: Start ApiGatewayDEV
     win_service:
       name: ApiGatewayDEV
       state: started
     when: ApiGatewayDEV_service.exists

### ApiGatewayPortal
   - name: get info on service ApiGatewayPortalDEV
     win_service:
       name: ApiGatewayPortalDEV
     register: ApiGatewayPortalDEV_service 
   - name: Start ApiGatewayPortalDEV
     win_service:
       name: ApiGatewayPortalDEV
       state: started
     when: ApiGatewayPortalDEV_service.exists

### AuthenticationService
   - name: get info on service AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
     register: AuthenticationServiceDEV_service
   - name: Start AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
       state: started
     when: AuthenticationServiceDEV_service.exists
     
### AutorizadorGenerico
   - name: get info on service AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
     register: AuthenticationServiceDEV_service 
   - name: Start AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
       state: started
     when: AuthenticationServiceDEV_service.exists

### SanatorioAllendeBackEnd
   - name: get info on service SanatorioAllendeBackEndDEV
     win_service:
       name: SanatorioAllendeBackEndDEV
     register: SanatorioAllendeBackEndDEV_service
   - name: Start SanatorioAllendeBackEndDEV
     win_service:
       name: SanatorioAllendeBackEndDEV
       state: started
     when: SanatorioAllendeBackEndDEV_service.exists

### SanatorioAllendeBackEndPortal
   - name: get info on service SanatorioAllendeBackEndPortalDEV
     win_service:
       name: SanatorioAllendeBackEndPortalDEV
     register: SanatorioAllendeBackEndPortalDEV_service
   - name: Start SanatorioAllendeBackEndPortalDEV
     win_service:
       name: SanatorioAllendeBackEndPortalDEV
       state: started
     when: SanatorioAllendeBackEndPortalDEV_service.exists

### Terminologia
   - name: get info on service TerminologiaDEV
     win_service:
       name: TerminologiaDEV
     register: TerminologiaDEV_service
   - name: Start TerminologiaDEV
     win_service:
       name: TerminologiaDEV
       state: started
     when: TerminologiaDEV_service.exists


### Stop Services workers
### BackupIMService
   - name: get info on service BackupIMServiceDEV
     win_service:
       name: BackupIMServiceDEV
     register: BackupIMServiceDEV_service
   - name: Start BackupIMServiceDEV
     win_service:
       name: BackupIMServiceDEV
       state: started
     when: BackupIMServiceDEV_service.exists

### CacheTerminologia
   - name: get info on service CacheTerminologiaDEV
     win_service:
       name: CacheTerminologiaDEV
     register: CacheTerminologiaDEV_service
   - name: Start CacheTerminologiaDEV
     win_service:
       name: CacheTerminologiaDEV
       state: started
     when: CacheTerminologiaDEV_service.exists

### ConfirmacionDeTurnosService
   - name: get info on service ConfirmacionDeTurnosServiceDEV
     win_service:
       name: ConfirmacionDeTurnosServiceDEV
     register: ConfirmacionDeTurnosServiceDEV_service
   - name: Start ConfirmacionDeTurnosServiceDEV
     win_service:
       name: ConfirmacionDeTurnosServiceDEV
       state: started
     when: ConfirmacionDeTurnosServiceDEV_service.exists

### FacturaElectronicaService
   - name: get info on service FacturaElectronicaServiceDEV
     win_service:
       name: FacturaElectronicaServiceDEV
     register: FacturaElectronicaServiceDEV_service
   - name: Start FacturaElectronicaServiceDEV
     win_service:
       name: FacturaElectronicaServiceDEV
       state: started
     when: FacturaElectronicaServiceDEV_service.exists

### ImportadorDeFarmacosService
   - name: get info on service ImportadorDeFarmacosServiceDEV
     win_service:
       name: ImportadorDeFarmacosServiceDEV
     register: ImportadorDeFarmacosServiceDEV_service
   - name: Start ImportadorDeFarmacosServiceDEV
     win_service:
       name: ImportadorDeFarmacosServiceDEV
       state: started
     when: ImportadorDeFarmacosServiceDEV_service.exists

### MessageIntegrationService
   - name: get info on service MessageIntegrationServiceDEV
     win_service:
       name: MessageIntegrationServiceDEV
     register: MessageIntegrationServiceDEV_service
   - name: Start MessageIntegrationServiceDEV
     win_service:
       name: MessageIntegrationServiceDEV
       state: started
     when: MessageIntegrationServiceDEV_service.exists

### NotificacionDeSolicitudesPendientes
   - name: get info on service NotificacionDeSolicitudesPendientesDEV
     win_service:
       name: NotificacionDeSolicitudesPendientesDEV
     register: NotificacionDeSolicitudesPendientesDEV_service
   - name: Start NotificacionDeSolicitudesPendientesDEV
     win_service:
       name: NotificacionDeSolicitudesPendientesDEV
       state: started
     when: NotificacionDeSolicitudesPendientesDEV_service.exists

### ReprocesadorDeIntegraciones
   - name: get info on service ReprocesadorDeIntegracionesDEV
     win_service:
       name: ReprocesadorDeIntegracionesDEV
     register: ReprocesadorDeIntegracionesDEV_service
   - name: Start ReprocesadorDeIntegracionesDEV
     win_service:
       name: ReprocesadorDeIntegracionesDEV
       state: started
     when: ReprocesadorDeIntegracionesDEV_service.exists

### ReprocesoAutorizacionesPendientesAud
   - name: get info on service ReprocesoAutorizacionesPendientesAudDEV
     win_service:
       name: ReprocesoAutorizacionesPendientesAudDEV
     register: ReprocesoAutorizacionesPendientesAudDEV_service
   - name: Start ReprocesoAutorizacionesPendientesAudDEV
     win_service:
       name: ReprocesoAutorizacionesPendientesAudDEV
       state: started
     when: ReprocesoAutorizacionesPendientesAudDEV_service.exists

### RisIntegrationService
   - name: get info on service RisIntegrationServiceDEV
     win_service:
       name: RisIntegrationServiceDEV
     register: RisIntegrationServiceDEV_service
   - name: Start RisIntegrationServiceDEV
     win_service:
       name: RisIntegrationServiceDEV
       state: started
     when: RisIntegrationServiceDEV_service.exists

### Start Services DogWatch

   - name: Start 'DogWatcherService{{ Environment }}'
     win_service:
       name: 'DogWatcherService{{ Environment }}'
       state: started