- hosts: backendevinfra
  vars:
   dirDeploy: C:\ServiciosSA\DEV\
   workSpace: /var/lib/jenkins/workspace/BackendDev/Deploy/Publish/Development/
   Environment: DEV

  tasks:

### Stopeo Servicios Backend
### Stop Services DogWatch

   - name: Stop DogWatcherServiceDEV
     win_service:
       name: DogWatcherServiceDEV
       state: stopped

### Stop Services webapi
### ApiGateway
   - name: get info on service ApiGatewayDEV
     win_service:
       name: ApiGatewayDEV
     register: ApiGatewayDEV_service  
   - name: Stop ApiGatewayDEV
     win_service:
       name: ApiGatewayDEV
       state: stopped
     when: ApiGatewayDEV_service.exists

### ApiGatewayPortal
   - name: get info on service ApiGatewayPortalDEV
     win_service:
       name: ApiGatewayPortalDEV
     register: ApiGatewayPortalDEV_service
   - name: Stop ApiGatewayPortalDEV
     win_service:
       name: ApiGatewayPortalDEV
       state: stopped
     when: ApiGatewayPortalDEV_service.exists

### AuthenticationService
   - name: get info on service AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
     register: AuthenticationServiceDEV_service
   - name: Stop AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
       state: stopped
     when: AuthenticationServiceDEV_service.exists
     
### AutorizadorGenerico
   - name: get info on service AutorizadorGenericoDEV
     win_service:
       name: AutorizadorGenericoDEV
     register: AutorizadorGenericoDEV_service
   - name: Stop AutorizadorGenericoDEV
     win_service:
       name: AutorizadorGenericoDEV
       state: stopped
     when: AutorizadorGenericoDEV_service.exists

### SanatorioAllendeBackEnd
   - name: get info on service SanatorioAllendeBackEndENV
     win_service:
       name: SanatorioAllendeBackEndENV
     register: SanatorioAllendeBackEndENV_service
   - name: Stop SanatorioAllendeBackEndENV
     win_service:
       name: SanatorioAllendeBackEndENV
       state: stopped
     when: SanatorioAllendeBackEndENV_service.exists

### SanatorioAllendeBackEndPortal
   - name: get info on service SanatorioAllendeBackEndPortalDEV
     win_service:
       name: SanatorioAllendeBackEndPortalDEV
     register: SanatorioAllendeBackEndPortalDEV_service
   - name: Stop SanatorioAllendeBackEndPortalDEV
     win_service:
       name: SanatorioAllendeBackEndPortalDEV
       state: stopped
     when: SanatorioAllendeBackEndPortalDEV_service.exists

### Terminologia
   - name: get info on service TerminologiaDEV
     win_service:
       name: TerminologiaDEV
     register: TerminologiaDEV_service
   - name: Stop TerminologiaDEV
     win_service:
       name: TerminologiaDEV
       state: stopped
     when: TerminologiaDEV_service.exists


### Stop Services workers
### BackupIMService
   - name: get info on service BackupIMServiceDEV
     win_service:
       name: BackupIMServiceDEV
     register: BackupIMServiceDEV_service
   - name: Stop BackupIMServiceDEV
     win_service:
       name: BackupIMServiceDEV
       state: stopped
     when: BackupIMServiceDEV_service.exists

### CacheTerminologia
   - name: get info on service CacheTerminologiaDEV
     win_service:
       name: CacheTerminologiaDEV
     register: CacheTerminologiaDEV_service
   - name: Stop CacheTerminologiaDEV
     win_service:
       name: CacheTerminologiaDEV
       state: stopped
     when: CacheTerminologiaDEV_service.exists

### ConfirmacionDeTurnosService
   - name: get info on service ConfirmacionDeTurnosServiceDEV
     win_service:
       name: ConfirmacionDeTurnosServiceDEV
     register: ConfirmacionDeTurnosServiceDEV_service
   - name: Stop ConfirmacionDeTurnosServiceDEV
     win_service:
       name: ConfirmacionDeTurnosServiceDEV
       state: stopped
     when: ConfirmacionDeTurnosServiceDEV_service.exists

### FacturaElectronicaService
   - name: get info on service FacturaElectronicaServiceDEV
     win_service:
       name: FacturaElectronicaServiceDEV
     register: FacturaElectronicaServiceDEV_service
   - name: Stop FacturaElectronicaServiceDEV
     win_service:
       name: FacturaElectronicaServiceDEV
       state: stopped
     when: FacturaElectronicaServiceDEV_service.exists

### ImportadorDeFarmacosService
   - name: get info on service ImportadorDeFarmacosServiceDEV
     win_service:
       name: ImportadorDeFarmacosServiceDEV
     register: ImportadorDeFarmacosServiceDEV_service
   - name: Stop ImportadorDeFarmacosServiceDEV
     win_service:
       name: ImportadorDeFarmacosServiceDEV
       state: stopped
     when: ImportadorDeFarmacosServiceDEV_service.exists

### MessageIntegrationService
   - name: get info on service MessageIntegrationServiceDEV
     win_service:
       name: MessageIntegrationServiceDEV
     register: MessageIntegrationServiceDEV_service
   - name: Stop MessageIntegrationServiceDEV
     win_service:
       name: MessageIntegrationServiceDEV
       state: stopped
     when: MessageIntegrationServiceDEV_service.exists

### NotificacionDeSolicitudesPendientes
   - name: get info on service NotificacionDeSolicitudesPendientesDEV
     win_service:
       name: NotificacionDeSolicitudesPendientesDEV
     register: NotificacionDeSolicitudesPendientesDEV_service
   - name: Stop NotificacionDeSolicitudesPendientesDEV
     win_service:
       name: NotificacionDeSolicitudesPendientesDEV
       state: stopped
     when: NotificacionDeSolicitudesPendientesDEV_service.exists

### ReprocesadorDeIntegraciones
   - name: get info on service SA-Reprocesador
     win_service:
       name: SA-Reprocesador
     register: SA-Reprocesador
   - name: Stop SA-Reprocesador
     win_service:
       name: SA-Reprocesador
       state: stopped
     when: SA-Reprocesador_service.exists

### ReprocesoAutorizacionesPendientesAud
   - name: get info on service ReprocesoAutorizacionesPendientesAudDEV
     win_service:
       name: ReprocesoAutorizacionesPendientesAudDEV
     register: ReprocesoAutorizacionesPendientesAudDEV_service
   - name: Stop ReprocesoAutorizacionesPendientesAudDEV
     win_service:
       name: ReprocesoAutorizacionesPendientesAudDEV
       state: stopped
     when: ReprocesoAutorizacionesPendientesAudDEV_service.exists

### RisIntegrationService
   - name: get info on service RisIntegrationServiceDEV
     win_service:
       name: RisIntegrationServiceDEV
     register: RisIntegrationServiceDEV_service
   - name: Stop RisIntegrationServiceDEV
     win_service:
       name: RisIntegrationServiceDEV
       state: stopped
     when: RisIntegrationServiceDEV_service.exists


### Starteo Servicios Backend
### Start Services webapi
### ApiGateway

   - name: Start ApiGatewayDEV
     win_service:
       name: ApiGatewayDEV
       state: started


### ApiGatewayPortal

   - name: Start ApiGatewayPortalDEV
     win_service:
       name: ApiGatewayPortalDEV
       state: started


### AuthenticationService

   - name: Start AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
       state: started

     
### AutorizadorGenerico

     register: AuthenticationServiceDEV_service 
   - name: Start AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
       state: started


### SanatorioAllendeBackEnd

   - name: Start SanatorioAllendeBackEndDEV
     win_service:
       name: SanatorioAllendeBackEndDEV
       state: started


### SanatorioAllendeBackEndPortal

   - name: Start SanatorioAllendeBackEndPortalDEV
     win_service:
       name: SanatorioAllendeBackEndPortalDEV
       state: started


### Terminologia

   - name: Start TerminologiaDEV
     win_service:
       name: TerminologiaDEV
       state: started



### Start Services workers
### BackupIMService

   - name: Start BackupIMServiceDEV
     win_service:
       name: BackupIMServiceDEV
       state: started


### CacheTerminologia

   - name: Start CacheTerminologiaDEV
     win_service:
       name: CacheTerminologiaDEV
       state: started


### ConfirmacionDeTurnosService
 
   - name: Start ConfirmacionDeTurnosServiceDEV
     win_service:
       name: ConfirmacionDeTurnosServiceDEV
       state: started

### FacturaElectronicaService

   - name: Start FacturaElectronicaServiceDEV
     win_service:
       name: FacturaElectronicaServiceDEV
       state: started


### ImportadorDeFarmacosService
#
#   - name: Start ImportadorDeFarmacosServiceDEV
#     win_service:
#       name: ImportadorDeFarmacosServiceDEV
#       state: started


### MessageIntegrationServiceDEV
   - name: Start MessageIntegrationServiceDEV
     win_service:
       name: MessageIntegrationServiceDEV
       state: started


### NotificacionDeSolicitudesPendientes

   - name: Start NotificacionDeSolicitudesPendientesDEV
     win_service:
       name: NotificacionDeSolicitudesPendientesDEV
       state: started


### ReprocesadorDeIntegraciones

   - name: Start SA-Reprocesador
     win_service:
       name: SA-Reprocesador
       state: started


### ReprocesoAutorizacionesPendientesAud

   - name: Start ReprocesoAutorizacionesPendientesAudDEV
     win_service:
       name: ReprocesoAutorizacionesPendientesAudDEV
       state: started

### RisIntegrationService
   - name: Start RisIntegrationServiceDEV
     win_service:
       name: RisIntegrationServiceDEV
       state: started

### Start Services DogWatch

   - name: Start DogWatcherServiceDEV
     win_service:
       name: DogWatcherServiceDEV
       state: started