- hosts: backendevinfra
  vars:
   dirDeploy: C:\ServiciosSA\DEV\
   workSpace: /var/lib/jenkins/workspace/BackendDev/Deploy/Publish/Development/
   Environment: DEV

  tasks:

### Stopeo Servicios Backend
### Stop Services DogWatch

   - name: Stop DogWatcherServiceDEV
     win_service:
       name: DogWatcherServiceDEV
       state: stopped

### Stop Services webapi
### ApiGateway
   - name: get info on service ApiGatewayDEV
     win_service:
       name: ApiGatewayDEV
     register: ApiGatewayDEV_service  
   - name: Stop ApiGatewayDEV
     win_service:
       name: ApiGatewayDEV
       state: stopped
     when: ApiGatewayDEV_service.exists

### ApiGatewayPortal
   - name: get info on service ApiGatewayPortalDEV
     win_service:
       name: ApiGatewayPortalDEV
     register: ApiGatewayPortalDEV_service
   - name: Stop ApiGatewayPortalDEV
     win_service:
       name: ApiGatewayPortalDEV
       state: stopped
     when: ApiGatewayPortalDEV_service.exists

### AuthenticationService
   - name: get info on service AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
     register: AuthenticationServiceDEV_service
   - name: Stop AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
       state: stopped
     when: AuthenticationServiceDEV_service.exists
     
### AutorizadorGenerico
   - name: get info on service AutorizadorGenericoDEV
     win_service:
       name: AutorizadorGenericoDEV
     register: AutorizadorGenericoDEV_service
   - name: Stop AutorizadorGenericoDEV
     win_service:
       name: AutorizadorGenericoDEV
       state: stopped
     when: AutorizadorGenericoDEV_service.exists

### SanatorioAllendeBackEnd
   - name: get info on service SanatorioAllendeBackEndENV
     win_service:
       name: SanatorioAllendeBackEndENV
     register: SanatorioAllendeBackEndENV_service
   - name: Stop SanatorioAllendeBackEndENV
     win_service:
       name: SanatorioAllendeBackEndENV
       state: stopped
     when: SanatorioAllendeBackEndENV_service.exists

### SanatorioAllendeBackEndPortal
   - name: get info on service SanatorioAllendeBackEndPortalDEV
     win_service:
       name: SanatorioAllendeBackEndPortalDEV
     register: SanatorioAllendeBackEndPortalDEV_service
   - name: Stop SanatorioAllendeBackEndPortalDEV
     win_service:
       name: SanatorioAllendeBackEndPortalDEV
       state: stopped
     when: SanatorioAllendeBackEndPortalDEV_service.exists

### Terminologia
   - name: get info on service TerminologiaDEV
     win_service:
       name: TerminologiaDEV
     register: TerminologiaDEV_service
   - name: Stop TerminologiaDEV
     win_service:
       name: TerminologiaDEV
       state: stopped
     when: TerminologiaDEV_service.exists


### Stop Services workers
### BackupIMService
   - name: get info on service BackupIMServiceDEV
     win_service:
       name: BackupIMServiceDEV
     register: BackupIMServiceDEV_service
   - name: Stop BackupIMServiceDEV
     win_service:
       name: BackupIMServiceDEV
       state: stopped
     when: BackupIMServiceDEV_service.exists

### CacheTerminologia
   - name: get info on service CacheTerminologiaDEV
     win_service:
       name: CacheTerminologiaDEV
     register: CacheTerminologiaDEV_service
   - name: Stop CacheTerminologiaDEV
     win_service:
       name: CacheTerminologiaDEV
       state: stopped
     when: CacheTerminologiaDEV_service.exists

### ConfirmacionDeTurnosService
   - name: get info on service ConfirmacionDeTurnosServiceDEV
     win_service:
       name: ConfirmacionDeTurnosServiceDEV
     register: ConfirmacionDeTurnosServiceDEV_service
   - name: Stop ConfirmacionDeTurnosServiceDEV
     win_service:
       name: ConfirmacionDeTurnosServiceDEV
       state: stopped
     when: ConfirmacionDeTurnosServiceDEV_service.exists

### FacturaElectronicaService
   - name: get info on service FacturaElectronicaServiceDEV
     win_service:
       name: FacturaElectronicaServiceDEV
     register: FacturaElectronicaServiceDEV_service
   - name: Stop FacturaElectronicaServiceDEV
     win_service:
       name: FacturaElectronicaServiceDEV
       state: stopped
     when: FacturaElectronicaServiceDEV_service.exists

### ImportadorDeFarmacosService
   - name: get info on service ImportadorDeFarmacosServiceDEV
     win_service:
       name: ImportadorDeFarmacosServiceDEV
     register: ImportadorDeFarmacosServiceDEV_service
   - name: Stop ImportadorDeFarmacosServiceDEV
     win_service:
       name: ImportadorDeFarmacosServiceDEV
       state: stopped
     when: ImportadorDeFarmacosServiceDEV_service.exists

### MessageIntegrationService
   - name: get info on service MessageIntegrationServiceDEV
     win_service:
       name: MessageIntegrationServiceDEV
     register: MessageIntegrationServiceDEV_service
   - name: Stop MessageIntegrationServiceDEV
     win_service:
       name: MessageIntegrationServiceDEV
       state: stopped
     when: MessageIntegrationServiceDEV_service.exists

### NotificacionDeSolicitudesPendientes
   - name: get info on service NotificacionDeSolicitudesPendientesDEV
     win_service:
       name: NotificacionDeSolicitudesPendientesDEV
     register: NotificacionDeSolicitudesPendientesDEV_service
   - name: Stop NotificacionDeSolicitudesPendientesDEV
     win_service:
       name: NotificacionDeSolicitudesPendientesDEV
       state: stopped
     when: NotificacionDeSolicitudesPendientesDEV_service.exists

### ReprocesadorDeIntegraciones
   - name: get info on service ReprocesadorDeIntegracionesDEV
     win_service:
       name: ReprocesadorDeIntegracionesDEV
     register: ReprocesadorDeIntegracionesDEV_service
   - name: Stop ReprocesadorDeIntegracionesDEV
     win_service:
       name: ReprocesadorDeIntegracionesDEV
       state: stopped
     when: ReprocesadorDeIntegracionesDEV_service.exists

### ReprocesoAutorizacionesPendientesAud
   - name: get info on service ReprocesoAutorizacionesPendientesAudDEV
     win_service:
       name: ReprocesoAutorizacionesPendientesAudDEV
     register: ReprocesoAutorizacionesPendientesAudDEV_service
   - name: Stop ReprocesoAutorizacionesPendientesAudDEV
     win_service:
       name: ReprocesoAutorizacionesPendientesAudDEV
       state: stopped
     when: ReprocesoAutorizacionesPendientesAudDEV_service.exists

### RisIntegrationService
   - name: get info on service RisIntegrationServiceDEV
     win_service:
       name: RisIntegrationServiceDEV
     register: RisIntegrationServiceDEV_service
   - name: Stop RisIntegrationServiceDEV
     win_service:
       name: RisIntegrationServiceDEV
       state: stopped
     when: RisIntegrationServiceDEV_service.exists


### Elimino Carpetas de Servicios

   - name: Delete ApiGatewayPortalService
     win_file:
       path: C:\ServiciosSA\DEV\ApiGatewayPortalService
       state: absent
   - name: Delete ApiGatewayService
     win_file:
       path: '"{{ dirDeploy }}"ApiGatewayService'
       state: absent
   - name: Delete AuthenticationService
     win_file:
       path: '"{{ dirDeploy }}"AuthenticationService'
       state: absent
   - name: Delete BackendService
     win_file:
       path: '"{{ dirDeploy }}"BackendService'
       state: absent
   - name: Delete BackupIMService
     win_file:
       path: '"{{ dirDeploy }}"BackupIMService'
       state: absent
   - name: Delete CacheTerminologiaService
     win_file:
       path: '"{{ dirDeploy }}"CacheTerminologiaService'
       state: absent
   - name: Delete ConfirmacionDeTurnosService
     win_file:
       path: '"{{ dirDeploy }}"ConfirmacionDeTurnosService'
       state: absent
   - name: Delete NotificacionDeSolicitudesPendientesService
     win_file:
       path: '"{{ dirDeploy }}"NotificacionDeSolicitudesPendientesService'
       state: absent
   - name: Delete PortalService
     win_file:
       path: '"{{ dirDeploy }}"PortalService'
       state: absent
   - name: Delete ReprocesadorDeIntegraciones
     win_file:
       path: '"{{ dirDeploy }}"ReprocesadorDeIntegraciones'
       state: absent
   - name: Delete ReprocesoAutorizacionesPendientesAud
     win_file:
       path: '"{{ dirDeploy }}"ReprocesoAutorizacionesPendientesAud'
       state: absent
   - name: Delete RisIntegrationService
     win_file:
       path: '"{{ dirDeploy }}"RisIntegrationService'
       state: absent
   - name: Delete TerminologiaService
     win_file:
       path: '"{{ dirDeploy }}"TerminologiaService'
       state: absent

### Creo Carpetas de Servicios
   - name: Create ApiGatewayPortalService
     win_file:
       path: '"{{ dirDeploy }}"ApiGatewayPortalService'
       state: directory
   - name: Create ApiGatewayService
     win_file:
       path: '"{{ dirDeploy }}"ApiGatewayService'
       state: directory
   - name: Create AuthenticationService
     win_file:
       path: '"{{ dirDeploy }}"AuthenticationService'
       state: directory
   - name: Create BackendService
     win_file:
       path: '"{{ dirDeploy }}"BackendService'
       state: directory
   - name: Create BackupIMService
     win_file:
       path: '"{{ dirDeploy }}"BackupIMService'
       state: directory
   - name: Create CacheTerminologiaService
     win_file:
       path: '"{{ dirDeploy }}"CacheTerminologiaService'
       state: directory
   - name: Create ConfirmacionDeTurnosService
     win_file:
       path: '"{{ dirDeploy }}"ConfirmacionDeTurnosService'
       state: directory
   - name: Create NotificacionDeSolicitudesPendientesService
     win_file:
       path: '"{{ dirDeploy }}"NotificacionDeSolicitudesPendientesService'
       state: directory
   - name: Create PortalService
     win_file:
       path: '"{{ dirDeploy }}"PortalService'
       state: directory
   - name: Create ReprocesadorDeIntegraciones
     win_file:
       path: '"{{ dirDeploy }}"ReprocesadorDeIntegraciones'
       state: directory
   - name: Create ReprocesoAutorizacionesPendientesAud
     win_file:
       path: '"{{ dirDeploy }}"ReprocesoAutorizacionesPendientesAud'
       state: directory
   - name: Create RisIntegrationService
     win_file:
       path: '"{{ dirDeploy }}"RisIntegrationService'
       state: directory
   - name: Create TerminologiaService
     win_file:
       path: '"{{ dirDeploy }}"TerminologiaService'
       state: directory

### Copio Carpetas de nuevo Deploy

   - name: Copy ApiGatewayPortalService
     win_copy:
       src: '{{ workSpace }}ApiGatewayPortalService'
       dest: "{{ dirDeploy }}"

   - name: Copy ApiGatewayService
     win_copy:
       src: '{{ workSpace }}ApiGatewayService'
       dest: "{{ dirDeploy }}"

   - name: Copy AuthenticationService
     win_copy:
       src: '{{ workSpace }}AuthenticationService'
       dest: "{{ dirDeploy }}"

   - name: Copy BackendService
     win_copy:
       src: '{{ workSpace }}BackendService'
       dest: "{{ dirDeploy }}"

   - name: Copy BackupIMService
     win_copy:
       src: '{{ workSpace }}BackupIMService'
       dest: "{{ dirDeploy }}"
  
   - name: Copy CacheTerminologiaService
     win_copy:
       src: '{{ workSpace }}CacheTerminologiaService'
       dest: "{{ dirDeploy }}"

   - name: Copy ConfirmacionDeTurnosService
     win_copy:
       src: '{{ workSpace }}ConfirmacionDeTurnosService'
       dest: "{{ dirDeploy }}"
  
   - name: Copy FacturaElectronicaService
     win_copy:
       src: '{{ workSpace }}FacturaElectronicaService'
       dest: "{{ dirDeploy }}"

   - name: Copy ImportadorDeFarmacosService
     win_copy:
       src: '{{ workSpace }}ImportadorDeFarmacosService'
       dest: "{{ dirDeploy }}"

   - name: Copy MessageIntegrationService
     win_copy:
       src: '{{ workSpace }}MessageIntegrationService'
       dest: "{{ dirDeploy }}"

   - name: Copy NotificacionDeSolicitudesPendientesService
     win_copy:
       src: '{{ workSpace }}NotificacionDeSolicitudesPendientesService'
       dest: "{{ dirDeploy }}"

   - name: Copy PortalService
     win_copy:
       src: '{{ workSpace }}PortalService'
       dest: "{{ dirDeploy }}"

   - name: Copy ReprocesadorDeIntegraciones
     win_copy:
       src: '{{ workSpace }}ReprocesadorDeIntegraciones'
       dest: "{{ dirDeploy }}"

   - name: Copy ReprocesoAutorizacionesPendientesAud
     win_copy:
       src: '{{ workSpace }}ReprocesoAutorizacionesPendientesAud'
       dest: "{{ dirDeploy }}"

   - name: Copy RisIntegrationService
     win_copy:
       src: '{{ workSpace }}RisIntegrationService'
       dest: "{{ dirDeploy }}"

   - name: Copy TerminologiaService
     win_copy:
       src: '{{ workSpace }}TerminologiaService'
       dest: "{{ dirDeploy }}"

### Starteo Servicios Backend
### Start Services webapi
### ApiGateway
   - name: get info on service ApiGatewayDEV
     win_service:
       name: ApiGatewayDEV
     register: ApiGatewayDEV_service 
   - name: Start ApiGatewayDEV
     win_service:
       name: ApiGatewayDEV
       state: started
     when: ApiGatewayDEV_service.exists

### ApiGatewayPortal
   - name: get info on service ApiGatewayPortalDEV
     win_service:
       name: ApiGatewayPortalDEV
     register: ApiGatewayPortalDEV_service 
   - name: Start ApiGatewayPortalDEV
     win_service:
       name: ApiGatewayPortalDEV
       state: started
     when: ApiGatewayPortalDEV_service.exists

### AuthenticationService
   - name: get info on service AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
     register: AuthenticationServiceDEV_service
   - name: Start AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
       state: started
     when: AuthenticationServiceDEV_service.exists
     
### AutorizadorGenerico
   - name: get info on service AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
     register: AuthenticationServiceDEV_service 
   - name: Start AuthenticationServiceDEV
     win_service:
       name: AuthenticationServiceDEV
       state: started
     when: AuthenticationServiceDEV_service.exists

### SanatorioAllendeBackEnd
   - name: get info on service SanatorioAllendeBackEndDEV
     win_service:
       name: SanatorioAllendeBackEndDEV
     register: SanatorioAllendeBackEndDEV_service
   - name: Start SanatorioAllendeBackEndDEV
     win_service:
       name: SanatorioAllendeBackEndDEV
       state: started
     when: SanatorioAllendeBackEndDEV_service.exists

### SanatorioAllendeBackEndPortal
   - name: get info on service SanatorioAllendeBackEndPortalDEV
     win_service:
       name: SanatorioAllendeBackEndPortalDEV
     register: SanatorioAllendeBackEndPortalDEV_service
   - name: Start SanatorioAllendeBackEndPortalDEV
     win_service:
       name: SanatorioAllendeBackEndPortalDEV
       state: started
     when: SanatorioAllendeBackEndPortalDEV_service.exists

### Terminologia
   - name: get info on service TerminologiaDEV
     win_service:
       name: TerminologiaDEV
     register: TerminologiaDEV_service
   - name: Start TerminologiaDEV
     win_service:
       name: TerminologiaDEV
       state: started
     when: TerminologiaDEV_service.exists


### Stop Services workers
### BackupIMService
   - name: get info on service BackupIMServiceDEV
     win_service:
       name: BackupIMServiceDEV
     register: BackupIMServiceDEV_service
   - name: Start BackupIMServiceDEV
     win_service:
       name: BackupIMServiceDEV
       state: started
     when: BackupIMServiceDEV_service.exists

### CacheTerminologia
   - name: get info on service CacheTerminologiaDEV
     win_service:
       name: CacheTerminologiaDEV
     register: CacheTerminologiaDEV_service
   - name: Start CacheTerminologiaDEV
     win_service:
       name: CacheTerminologiaDEV
       state: started
     when: CacheTerminologiaDEV_service.exists

### ConfirmacionDeTurnosService
   - name: get info on service ConfirmacionDeTurnosServiceDEV
     win_service:
       name: ConfirmacionDeTurnosServiceDEV
     register: ConfirmacionDeTurnosServiceDEV_service
   - name: Start ConfirmacionDeTurnosServiceDEV
     win_service:
       name: ConfirmacionDeTurnosServiceDEV
       state: started
     when: ConfirmacionDeTurnosServiceDEV_service.exists

### FacturaElectronicaService
   - name: get info on service FacturaElectronicaServiceDEV
     win_service:
       name: FacturaElectronicaServiceDEV
     register: FacturaElectronicaServiceDEV_service
   - name: Start FacturaElectronicaServiceDEV
     win_service:
       name: FacturaElectronicaServiceDEV
       state: started
     when: FacturaElectronicaServiceDEV_service.exists

### ImportadorDeFarmacosService
   - name: get info on service ImportadorDeFarmacosServiceDEV
     win_service:
       name: ImportadorDeFarmacosServiceDEV
     register: ImportadorDeFarmacosServiceDEV_service
   - name: Start ImportadorDeFarmacosServiceDEV
     win_service:
       name: ImportadorDeFarmacosServiceDEV
       state: started
     when: ImportadorDeFarmacosServiceDEV_service.exists

### MessageIntegrationService
   - name: get info on service MessageIntegrationServiceDEV
     win_service:
       name: MessageIntegrationServiceDEV
     register: MessageIntegrationServiceDEV_service
   - name: Start MessageIntegrationServiceDEV
     win_service:
       name: MessageIntegrationServiceDEV
       state: started
     when: MessageIntegrationServiceDEV_service.exists

### NotificacionDeSolicitudesPendientes
   - name: get info on service NotificacionDeSolicitudesPendientesDEV
     win_service:
       name: NotificacionDeSolicitudesPendientesDEV
     register: NotificacionDeSolicitudesPendientesDEV_service
   - name: Start NotificacionDeSolicitudesPendientesDEV
     win_service:
       name: NotificacionDeSolicitudesPendientesDEV
       state: started
     when: NotificacionDeSolicitudesPendientesDEV_service.exists

### ReprocesadorDeIntegraciones
   - name: get info on service ReprocesadorDeIntegracionesDEV
     win_service:
       name: ReprocesadorDeIntegracionesDEV
     register: ReprocesadorDeIntegracionesDEV_service
   - name: Start ReprocesadorDeIntegracionesDEV
     win_service:
       name: ReprocesadorDeIntegracionesDEV
       state: started
     when: ReprocesadorDeIntegracionesDEV_service.exists

### ReprocesoAutorizacionesPendientesAud
   - name: get info on service ReprocesoAutorizacionesPendientesAudDEV
     win_service:
       name: ReprocesoAutorizacionesPendientesAudDEV
     register: ReprocesoAutorizacionesPendientesAudDEV_service
   - name: Start ReprocesoAutorizacionesPendientesAudDEV
     win_service:
       name: ReprocesoAutorizacionesPendientesAudDEV
       state: started
     when: ReprocesoAutorizacionesPendientesAudDEV_service.exists

### RisIntegrationService
   - name: get info on service RisIntegrationServiceDEV
     win_service:
       name: RisIntegrationServiceDEV
     register: RisIntegrationServiceDEV_service
   - name: Start RisIntegrationServiceDEV
     win_service:
       name: RisIntegrationServiceDEV
       state: started
     when: RisIntegrationServiceDEV_service.exists

### Start Services DogWatch

   - name: Start 'DogWatcherService{{ Environment }}'
     win_service:
       name: 'DogWatcherService{{ Environment }}'
       state: started